### ISSUE TITLE
Unable to install "Pyrite Financial"

### ISSUE THREAD

**Issue by davidfekke** [blackberry/BlackBerry-Spark-SDK-iOS-Samples#6]
The logs provide the following error when trying to install on the device.

Details

Unable to install "Pyrite Financial"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620375
User Info: {
    DVTErrorCreationDateKey = "2022-02-02 19:42:09 +0000";
    IDERunOperationFailingWorker = IDEInstalliPhoneLauncher;
}
--
The code signature version is no longer supported.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620375
User Info: {
    DVTRadarComponentKey = 261622;
    MobileDeviceErrorCode = "(0xE8008029)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x000000010e24a076 DTDKCreateNSErrorFromAMDErrorCode + 220
	1   DTDeviceKitBase                     0x000000010e2886e8 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 155
	2   DVTFoundation                       0x00000001024a8fb4 DVTInvokeWithStrongOwnership + 71
	3   DTDeviceKitBase                     0x000000010e288432 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1420
	4   IDEiOSSupportCore                   0x000000010ad2a9ea __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.292 + 3508
	5   DVTFoundation                       0x00000001025dd98b __DVT_CALLING_CLIENT_BLOCK__ + 7
	6   DVTFoundation                       0x00000001025df0f7 __DVTDispatchAsync_block_invoke + 931
	7   libdispatch.dylib                   0x00007ff803d34ad8 _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007ff803d35cc9 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007ff803d3bcee _dispatch_lane_serial_drain + 696
	10  libdispatch.dylib                   0x00007ff803d3c7c8 _dispatch_lane_invoke + 366
	11  libdispatch.dylib                   0x00007ff803d467e1 _dispatch_workloop_worker_thread + 758
	12  libsystem_pthread.dylib             0x00007ff803ee9074 _pthread_wqthread + 326
	13  libsystem_pthread.dylib             0x00007ff803ee7ffb start_wqthread + 15
);
}
--

Analytics Event: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_model" = "iPhone14,2";
    "device_osBuild" = "15.3 (19D50)";
    "device_platform" = "com.apple.platform.iphoneos";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 1;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 4110;
    "operation_errorCode" = "-402620375";
    "operation_errorDomain" = "com.apple.dt.MobileDeviceErrorDomain";
    "operation_errorWorker" = IDEInstalliPhoneLauncher;
    "operation_name" = IDEiPhoneRunOperationWorkerGroup;
    "param_consoleMode" = 0;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 5;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.iphoneos";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 0;
    "param_launcher_substyle" = 0;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_runnable_swiftVersion" = "5.5.2";
    "param_runnable_type" = 2;
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "iphoneos15.2";
    "sdk_osVersion" = "15.2";
    "sdk_variant" = iphoneos;
}
--

System Information

macOS Version 12.2 (Build 21D49)
Xcode 13.2.1 (19586) (Build 13C100)
Timestamp: 2022-02-02T14:42:09-05:00

**Comment by matt-falkner** [comment]
Hi David, 

I've tried replicating your issue with 
- xcode 13.2.1
- Mac os 11.6.1 
- a fresh clone of this project 

Following the `README.md` I was able to run it on a physical device iOS 14 iPhone SE 2 without encountering this error. 

----

After some research, I believe this error is likely environmental. 

Here's a post on apple's developer forum with the same [issue](https://developer.apple.com/forums/thread/679182)
And another popular post on [stackoverflow]( https://stackoverflow.com/questions/68467306/the-code-signature-version-is-no-longer-supported)

I would also recommend clearing your `DerivedData` 

If you have any more issue/questions don't hesitate to reach out. 

-Matt

**Comment by davidfekke** [comment]
Hey Matt,

I was able to get this to deploy to the device by making the following change;

Under "Frameworkd, Libraries, and Embeded Content", I changed the Pods_Pyrite_Financial.framework from "Embed and Sign" to Do Not Embed". I can now run the example app on a device.

Thanks,
David Fekke
